import { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from "@/components/ui/form";
import { Progress } from "@/components/ui/progress";
import { useToast } from "@/hooks/use-toast";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Building2, Upload, FileSignature, QrCode, ArrowRight, ArrowLeft, Check } from "lucide-react";
import { isUnauthorizedError } from "@/lib/authUtils";
import { useLocation } from "wouter";

const businessInfoSchema = z.object({
  businessName: z.string().min(1, "Business name is required"),
  address: z.string().optional(),
  city: z.string().optional(),
  postcode: z.string().optional(),
  phone: z.string().optional(),
  email: z.string().email().optional().or(z.literal("")),
  vatNumber: z.string().optional(),
  companyNumber: z.string().optional(),
  headerText: z.string().optional(),
  footerText: z.string().optional(),
  paymentLink: z.string().url().optional().or(z.literal("")),
  primaryColor: z.string().default("#1e40af"),
});

type BusinessInfoFormData = z.infer<typeof businessInfoSchema>;

export default function Onboarding() {
  const [step, setStep] = useState(1);
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [signatureFile, setSignatureFile] = useState<File | null>(null);
  const [useAutoDesign, setUseAutoDesign] = useState(true);
  const { toast } = useToast();
  const [, setLocation] = useLocation();

  const totalSteps = 5;
  const progress = (step / totalSteps) * 100;

  const form = useForm<BusinessInfoFormData>({
    resolver: zodResolver(businessInfoSchema),
    defaultValues: {
      businessName: "",
      address: "",
      city: "",
      postcode: "",
      phone: "",
      email: "",
      vatNumber: "",
      companyNumber: "",
      headerText: "",
      footerText: "",
      paymentLink: "",
      primaryColor: "#1e40af",
    },
  });

  const completeMutation = useMutation({
    mutationFn: async (data: any) => {
      return await apiRequest("POST", "/api/business/complete-onboarding", data);
    },
    onSuccess: () => {
      toast({
        title: "Welcome!",
        description: "Your business profile is complete. Let's get started!",
      });
      queryClient.invalidateQueries({ queryKey: ["/api/business"] });
      setLocation("/");
    },
    onError: (error: Error) => {
      if (isUnauthorizedError(error)) {
        toast({
          title: "Unauthorized",
          description: "You are logged out. Logging in again...",
          variant: "destructive",
        });
        setTimeout(() => {
          window.location.href = "/api/login";
        }, 500);
        return;
      }
      toast({
        title: "Error",
        description: "Failed to complete onboarding. Please try again.",
        variant: "destructive",
      });
    },
  });

  const onSubmit = (data: BusinessInfoFormData) => {
    completeMutation.mutate({
      ...data,
      useAutoGeneratedDesign: useAutoDesign,
      logo: logoFile ? "uploaded" : null,
      signature: signatureFile ? "uploaded" : null,
    });
  };

  const nextStep = () => {
    if (step < totalSteps) setStep(step + 1);
  };

  const prevStep = () => {
    if (step > 1) setStep(step - 1);
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>, type: 'logo' | 'signature') => {
    const file = e.target.files?.[0];
    if (file) {
      if (type === 'logo') {
        setLogoFile(file);
      } else {
        setSignatureFile(file);
      }
    }
  };

  return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <div className="w-full max-w-3xl">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold mb-2">Welcome to CRM Launch</h1>
          <p className="text-lg text-muted-foreground">
            Let's set up your business profile in just a few steps
          </p>
        </div>

        <Card className="p-8">
          {/* Progress Bar */}
          <div className="mb-8">
            <div className="flex justify-between mb-2">
              <span className="text-sm font-medium">Step {step} of {totalSteps}</span>
              <span className="text-sm text-muted-foreground">{Math.round(progress)}% complete</span>
            </div>
            <Progress value={progress} className="h-2" data-testid="progress-onboarding" />
          </div>

          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              {/* Step 1: Business Information */}
              {step === 1 && (
                <div className="space-y-4" data-testid="step-business-info">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-md bg-primary/10 flex items-center justify-center">
                      <Building2 className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h2 className="text-2xl font-semibold">Business Information</h2>
                      <p className="text-sm text-muted-foreground">Tell us about your business</p>
                    </div>
                  </div>

                  <FormField
                    control={form.control}
                    name="businessName"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Business Name *</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., Acme Plumbing Ltd" {...field} data-testid="input-business-name" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="email"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Business Email</FormLabel>
                          <FormControl>
                            <Input type="email" placeholder="info@business.com" {...field} data-testid="input-business-email" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="phone"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Phone Number</FormLabel>
                          <FormControl>
                            <Input placeholder="020 1234 5678" {...field} data-testid="input-phone" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <FormField
                    control={form.control}
                    name="address"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Address</FormLabel>
                        <FormControl>
                          <Input placeholder="123 High Street" {...field} data-testid="input-address" />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="city"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>City</FormLabel>
                          <FormControl>
                            <Input placeholder="London" {...field} data-testid="input-city" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="postcode"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Postcode</FormLabel>
                          <FormControl>
                            <Input placeholder="SW1A 1AA" {...field} data-testid="input-postcode" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      control={form.control}
                      name="vatNumber"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>VAT Number</FormLabel>
                          <FormControl>
                            <Input placeholder="GB123456789" {...field} data-testid="input-vat" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="companyNumber"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Company Number</FormLabel>
                          <FormControl>
                            <Input placeholder="12345678" {...field} data-testid="input-company-number" />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
              )}

              {/* Step 2: Logo */}
              {step === 2 && (
                <div className="space-y-4" data-testid="step-logo">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-md bg-primary/10 flex items-center justify-center">
                      <Upload className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h2 className="text-2xl font-semibold">Business Logo</h2>
                      <p className="text-sm text-muted-foreground">Upload your logo or let us create one</p>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="flex items-center gap-4">
                      <Button
                        type="button"
                        variant={useAutoDesign ? "default" : "outline"}
                        onClick={() => setUseAutoDesign(true)}
                        data-testid="button-auto-design"
                      >
                        Auto-Generate Design
                      </Button>
                      <Button
                        type="button"
                        variant={!useAutoDesign ? "default" : "outline"}
                        onClick={() => setUseAutoDesign(false)}
                        data-testid="button-upload-logo"
                      >
                        Upload My Own
                      </Button>
                    </div>

                    {useAutoDesign ? (
                      <Card className="p-6 bg-muted">
                        <h3 className="font-semibold mb-2">We'll create a professional design for you</h3>
                        <p className="text-sm text-muted-foreground mb-4">
                          Based on your business name, we'll generate a clean, professional logo and letterhead design automatically.
                        </p>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Check className="h-4 w-4 text-primary" />
                          <span>Professional typography</span>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Check className="h-4 w-4 text-primary" />
                          <span>Branded colors</span>
                        </div>
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Check className="h-4 w-4 text-primary" />
                          <span>Consistent across all documents</span>
                        </div>
                      </Card>
                    ) : (
                      <div>
                        <label htmlFor="logo-upload" className="block mb-2 text-sm font-medium">
                          Upload Logo File
                        </label>
                        <Input
                          id="logo-upload"
                          type="file"
                          accept="image/*"
                          onChange={(e) => handleFileChange(e, 'logo')}
                          data-testid="input-logo-file"
                        />
                        {logoFile && (
                          <p className="text-sm text-muted-foreground mt-2">
                            Selected: {logoFile.name}
                          </p>
                        )}
                      </div>
                    )}

                    <FormField
                      control={form.control}
                      name="primaryColor"
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Primary Brand Color</FormLabel>
                          <FormControl>
                            <div className="flex items-center gap-3">
                              <Input type="color" {...field} className="w-20 h-11" data-testid="input-color" />
                              <Input value={field.value} onChange={field.onChange} placeholder="#1e40af" />
                            </div>
                          </FormControl>
                          <FormDescription>
                            This color will be used in your documents
                          </FormDescription>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
              )}

              {/* Step 3: Header & Footer */}
              {step === 3 && (
                <div className="space-y-4" data-testid="step-header-footer">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-md bg-primary/10 flex items-center justify-center">
                      <FileSignature className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h2 className="text-2xl font-semibold">Header & Footer</h2>
                      <p className="text-sm text-muted-foreground">Customize your document templates</p>
                    </div>
                  </div>

                  <FormField
                    control={form.control}
                    name="headerText"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Header Text (Optional)</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="E.g., Professional Services Since 2020"
                            {...field}
                            rows={2}
                            data-testid="input-header"
                          />
                        </FormControl>
                        <FormDescription>
                          Appears at the top of your documents
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="footerText"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Footer Text (Optional)</FormLabel>
                        <FormControl>
                          <Textarea
                            placeholder="E.g., Terms & conditions apply. Payment due within 30 days."
                            {...field}
                            rows={2}
                            data-testid="input-footer"
                          />
                        </FormControl>
                        <FormDescription>
                          Appears at the bottom of your documents
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              )}

              {/* Step 4: Signature */}
              {step === 4 && (
                <div className="space-y-4" data-testid="step-signature">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-md bg-primary/10 flex items-center justify-center">
                      <FileSignature className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h2 className="text-2xl font-semibold">Digital Signature</h2>
                      <p className="text-sm text-muted-foreground">Add a professional touch to your documents</p>
                    </div>
                  </div>

                  <div>
                    <label htmlFor="signature-upload" className="block mb-2 text-sm font-medium">
                      Upload Signature Image (Optional)
                    </label>
                    <Input
                      id="signature-upload"
                      type="file"
                      accept="image/*"
                      onChange={(e) => handleFileChange(e, 'signature')}
                      data-testid="input-signature-file"
                    />
                    {signatureFile && (
                      <p className="text-sm text-muted-foreground mt-2">
                        Selected: {signatureFile.name}
                      </p>
                    )}
                    <p className="text-sm text-muted-foreground mt-2">
                      You can add this later from settings if you don't have one ready
                    </p>
                  </div>
                </div>
              )}

              {/* Step 5: Payment Details */}
              {step === 5 && (
                <div className="space-y-4" data-testid="step-payment">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-md bg-primary/10 flex items-center justify-center">
                      <QrCode className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <h2 className="text-2xl font-semibold">Payment Information</h2>
                      <p className="text-sm text-muted-foreground">Help customers pay you faster</p>
                    </div>
                  </div>

                  <FormField
                    control={form.control}
                    name="paymentLink"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Payment Link or QR Code URL (Optional)</FormLabel>
                        <FormControl>
                          <Input
                            type="url"
                            placeholder="https://pay.yoursite.com/invoice"
                            {...field}
                            data-testid="input-payment-link"
                          />
                        </FormControl>
                        <FormDescription>
                          Add a payment link that will be included in invoices (e.g., PayPal, Stripe, bank payment page)
                        </FormDescription>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <Card className="p-4 bg-muted">
                    <p className="text-sm text-muted-foreground">
                      💡 Tip: You can update these details anytime from your settings page
                    </p>
                  </Card>
                </div>
              )}

              {/* Navigation Buttons */}
              <div className="flex justify-between pt-6 border-t border-border">
                {step > 1 && (
                  <Button
                    type="button"
                    variant="outline"
                    onClick={prevStep}
                    data-testid="button-prev"
                  >
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Previous
                  </Button>
                )}
                {step < totalSteps ? (
                  <Button
                    type="button"
                    onClick={nextStep}
                    className="ml-auto"
                    data-testid="button-next"
                  >
                    Next
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                ) : (
                  <Button
                    type="submit"
                    className="ml-auto"
                    disabled={completeMutation.isPending}
                    data-testid="button-complete"
                  >
                    {completeMutation.isPending ? "Saving..." : "Complete Setup"}
                    <Check className="ml-2 h-4 w-4" />
                  </Button>
                )}
              </div>
            </form>
          </Form>
        </Card>
      </div>
    </div>
  );
}
